mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
	# ex: /polls/
    url(r'^$', views.IndexView.as_view(), name='index'),
	#ex: /polls/5/
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
	#ex: /polls/5/results/
	url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
	#ex: /polls/5/vote/
	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
	#ex: humans page
	url(r'^humans/$', views.humans, name='h'),
	#ex: simple form
	url(r'^username/$', views.get_username, name='username'),
	#ex: purchase form
	url(r'^purchase/$', views.purchase, name='purchase'),
]

polls/models.py
from __future__ import unicode_literals
import datetime
from django.utils.encoding import python_2_unicode_compatible
from django.db import models
from django.utils import timezone


@python_2_unicode_compatible
class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	def __str__(self):
		return self.question_text
 	def was_published_recently(self):
		return timezone.now() - datetime.timedelta(days=1) <= self.pub_date <= timezone.now()

@python_2_unicode_compatible
class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text

GENDER_CHOICES = (
	('M', 'Male'),
	('F', 'Female'),
)

class Human(models.Model):
	name = models.CharField(max_length=64)
	surname = models.CharField(max_length=64)
	height = models.IntegerField(default=0)
	date_of_birth = models.DateTimeField()
	gender = models.CharField(max_length=1, default='M', choices=GENDER_CHOICES)
	def __str__(self):
		return self.name + " " + self.surname

class Shoe(models.Model):
	name = models.CharField(max_length=64)
	manufacturer = models.CharField(max_length=64)
	price = models.DecimalField(max_digits=5, decimal_places=2)
	def __str__(self):
		return self.name

class Purchase(models.Model):
	buyer = models.ForeignKey(Human, on_delete=models.CASCADE)
	item = models.ForeignKey(Shoe, on_delete=models.CASCADE)
	quantity = models.IntegerField(default=1)
	date = models.DateTimeField()
	def __str__(self):
		return self.buyer.name + " " + self.item.name

polls/forms.py
from django import forms
from polls.models import Human, Purchase

class NameForm(forms.Form):
	username = forms.CharField(max_length=64)

class AutoForm(forms.ModelForm):
	class Meta:
		model = Human
		fields = '__all__'

class PurchaseForm(forms.ModelForm):
	class Meta:
		model = Purchase
		fields = '__all__'

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.urls import reverse
from django.utils import timezone
from .models import Choice, Question, Human
from .forms import NameForm
from .forms import AutoForm
from .forms import PurchaseForm


class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'
	
	def get_queryset(self):
		"""Return the last five published questions."""
		return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
	model = Question
	template_name = 'polls/detail.html'
	
	def get_queryset(self):
		"""
		Excludes any questions tha aren't published yet.
		"""
		return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
	model = Question
	template_name = 'polls/results.html'

def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'polls/detail.html', {
			'question': question,
			'error_message': "You didn't select a choice.",
		})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def humans(request):
	humans_list = Human.objects.all()
	template = loader.get_template('polls/humans.html')
	context = {
		'humans_list': humans_list,
	}
	return HttpResponse(template.render(context, request))

def get_username(request):
	if request.method == 'POST':
		form = AutoForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data['name']
			form.save()
			return HttpResponse('Thank you %s!' % username);
	else:
		form = AutoForm()
	return render(request, 'polls/username.html', {'form': form})

def purchase(request):
	if request.method == 'POST':
		form = PurchaseForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponse('Have a nice day!')
	else:
		form = PurchaseForm()
	return render(request, 'polls/purchase.html', {'form': form})

polls/templates/polls/detail.html
<h1> {{question.question_text}} </h1>
{% if error_message %} <p><strong> {{ error_message }}</strong></p> {% endif %}
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
	<label for="choice{{ forloop.counter }}"> {{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/humans.html
{% if humans_list %}
	<ul>
	{% for human in humans_list %}
		<li>{{human}}</li>
	{% endfor %}
	</ul>
{% else %}
	<p>no humans here</p>
{% endif %}

polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
{% if latest_question_list %}
	<ul>
	{% for question in latest_question_list %}
		<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No polls are available.</p>
{% endif %}

polls/templates/polls/purchase.html
<form action="{% url 'polls:purchase' %}" method="post">
	{% csrf_token %}
	{{ form }}
	<input type="submit" value="Submit" />
</form>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

polls/templates/polls/username.html
<form action="{% url 'polls:username' %}" method="post">
	{% csrf_token %}
	{{ form }}
	<input type="submit" value="Submit" />
</form>